// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { PredecessorAPI } from './predecessor-api'
import { Predecessor, CopyPredecessorToPredecessorAPI } from './predecessor'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { TaskAPI } from './task-api'

@Injectable({
  providedIn: 'root'
})
export class PredecessorService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  PredecessorServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private predecessorsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.predecessorsUrl = origin + '/api/github.com/fullstack-lang/gongplanning/go/v1/predecessors';
  }

  /** GET predecessors from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI[]> {
    return this.getPredecessors(GONG__StackPath, frontRepo)
  }
  getPredecessors(GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<PredecessorAPI[]>(this.predecessorsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<PredecessorAPI[]>('getPredecessors', []))
      );
  }

  /** GET predecessor by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI> {
    return this.getPredecessor(id, GONG__StackPath, frontRepo)
  }
  getPredecessor(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.predecessorsUrl}/${id}`;
    return this.http.get<PredecessorAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched predecessor id=${id}`)),
      catchError(this.handleError<PredecessorAPI>(`getPredecessor id=${id}`))
    );
  }

  // postFront copy predecessor to a version with encoded pointers and post to the back
  postFront(predecessor: Predecessor, GONG__StackPath: string): Observable<PredecessorAPI> {
    let predecessorAPI = new PredecessorAPI
    CopyPredecessorToPredecessorAPI(predecessor, predecessorAPI)
    const id = typeof predecessorAPI === 'number' ? predecessorAPI : predecessorAPI.ID
    const url = `${this.predecessorsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<PredecessorAPI>(url, predecessorAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<PredecessorAPI>('postPredecessor'))
    );
  }
  
  /** POST: add a new predecessor to the server */
  post(predecessordb: PredecessorAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI> {
    return this.postPredecessor(predecessordb, GONG__StackPath, frontRepo)
  }
  postPredecessor(predecessordb: PredecessorAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<PredecessorAPI>(this.predecessorsUrl, predecessordb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted predecessordb id=${predecessordb.ID}`)
      }),
      catchError(this.handleError<PredecessorAPI>('postPredecessor'))
    );
  }

  /** DELETE: delete the predecessordb from the server */
  delete(predecessordb: PredecessorAPI | number, GONG__StackPath: string): Observable<PredecessorAPI> {
    return this.deletePredecessor(predecessordb, GONG__StackPath)
  }
  deletePredecessor(predecessordb: PredecessorAPI | number, GONG__StackPath: string): Observable<PredecessorAPI> {
    const id = typeof predecessordb === 'number' ? predecessordb : predecessordb.ID;
    const url = `${this.predecessorsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<PredecessorAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted predecessordb id=${id}`)),
      catchError(this.handleError<PredecessorAPI>('deletePredecessor'))
    );
  }

  // updateFront copy predecessor to a version with encoded pointers and update to the back
  updateFront(predecessor: Predecessor, GONG__StackPath: string): Observable<PredecessorAPI> {
    let predecessorAPI = new PredecessorAPI
    CopyPredecessorToPredecessorAPI(predecessor, predecessorAPI)
    const id = typeof predecessorAPI === 'number' ? predecessorAPI : predecessorAPI.ID
    const url = `${this.predecessorsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<PredecessorAPI>(url, predecessorAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<PredecessorAPI>('updatePredecessor'))
    );
  }

  /** PUT: update the predecessordb on the server */
  update(predecessordb: PredecessorAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI> {
    return this.updatePredecessor(predecessordb, GONG__StackPath, frontRepo)
  }
  updatePredecessor(predecessordb: PredecessorAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PredecessorAPI> {
    const id = typeof predecessordb === 'number' ? predecessordb : predecessordb.ID;
    const url = `${this.predecessorsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<PredecessorAPI>(url, predecessordb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated predecessordb id=${predecessordb.ID}`)
      }),
      catchError(this.handleError<PredecessorAPI>('updatePredecessor'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in PredecessorService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("PredecessorService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
