// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { ProjectAPI } from './project-api'
import { Project, CopyProjectToProjectAPI } from './project'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class ProjectService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ProjectServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private projectsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.projectsUrl = origin + '/api/github.com/fullstack-lang/gongplanning/go/v1/projects';
  }

  /** GET projects from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI[]> {
    return this.getProjects(GONG__StackPath, frontRepo)
  }
  getProjects(GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ProjectAPI[]>(this.projectsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<ProjectAPI[]>('getProjects', []))
      );
  }

  /** GET project by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI> {
    return this.getProject(id, GONG__StackPath, frontRepo)
  }
  getProject(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.projectsUrl}/${id}`;
    return this.http.get<ProjectAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched project id=${id}`)),
      catchError(this.handleError<ProjectAPI>(`getProject id=${id}`))
    );
  }

  // postFront copy project to a version with encoded pointers and post to the back
  postFront(project: Project, GONG__StackPath: string): Observable<ProjectAPI> {
    let projectAPI = new ProjectAPI
    CopyProjectToProjectAPI(project, projectAPI)
    const id = typeof projectAPI === 'number' ? projectAPI : projectAPI.ID
    const url = `${this.projectsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ProjectAPI>(url, projectAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ProjectAPI>('postProject'))
    );
  }
  
  /** POST: add a new project to the server */
  post(projectdb: ProjectAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI> {
    return this.postProject(projectdb, GONG__StackPath, frontRepo)
  }
  postProject(projectdb: ProjectAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ProjectAPI>(this.projectsUrl, projectdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted projectdb id=${projectdb.ID}`)
      }),
      catchError(this.handleError<ProjectAPI>('postProject'))
    );
  }

  /** DELETE: delete the projectdb from the server */
  delete(projectdb: ProjectAPI | number, GONG__StackPath: string): Observable<ProjectAPI> {
    return this.deleteProject(projectdb, GONG__StackPath)
  }
  deleteProject(projectdb: ProjectAPI | number, GONG__StackPath: string): Observable<ProjectAPI> {
    const id = typeof projectdb === 'number' ? projectdb : projectdb.ID;
    const url = `${this.projectsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ProjectAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted projectdb id=${id}`)),
      catchError(this.handleError<ProjectAPI>('deleteProject'))
    );
  }

  // updateFront copy project to a version with encoded pointers and update to the back
  updateFront(project: Project, GONG__StackPath: string): Observable<ProjectAPI> {
    let projectAPI = new ProjectAPI
    CopyProjectToProjectAPI(project, projectAPI)
    const id = typeof projectAPI === 'number' ? projectAPI : projectAPI.ID
    const url = `${this.projectsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<ProjectAPI>(url, projectAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ProjectAPI>('updateProject'))
    );
  }

  /** PUT: update the projectdb on the server */
  update(projectdb: ProjectAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI> {
    return this.updateProject(projectdb, GONG__StackPath, frontRepo)
  }
  updateProject(projectdb: ProjectAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ProjectAPI> {
    const id = typeof projectdb === 'number' ? projectdb : projectdb.ID;
    const url = `${this.projectsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ProjectAPI>(url, projectdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated projectdb id=${projectdb.ID}`)
      }),
      catchError(this.handleError<ProjectAPI>('updateProject'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ProjectService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ProjectService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
