// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { TaskAPI } from './task-api'
import { Task, CopyTaskToTaskAPI } from './task'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { PredecessorAPI } from './predecessor-api'

@Injectable({
  providedIn: 'root'
})
export class TaskService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TaskServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private tasksUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.tasksUrl = origin + '/api/github.com/fullstack-lang/gongplanning/go/v1/tasks';
  }

  /** GET tasks from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI[]> {
    return this.getTasks(GONG__StackPath, frontRepo)
  }
  getTasks(GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<TaskAPI[]>(this.tasksUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<TaskAPI[]>('getTasks', []))
      );
  }

  /** GET task by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI> {
    return this.getTask(id, GONG__StackPath, frontRepo)
  }
  getTask(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.tasksUrl}/${id}`;
    return this.http.get<TaskAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched task id=${id}`)),
      catchError(this.handleError<TaskAPI>(`getTask id=${id}`))
    );
  }

  // postFront copy task to a version with encoded pointers and post to the back
  postFront(task: Task, GONG__StackPath: string): Observable<TaskAPI> {
    let taskAPI = new TaskAPI
    CopyTaskToTaskAPI(task, taskAPI)
    const id = typeof taskAPI === 'number' ? taskAPI : taskAPI.ID
    const url = `${this.tasksUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TaskAPI>(url, taskAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<TaskAPI>('postTask'))
    );
  }
  
  /** POST: add a new task to the server */
  post(taskdb: TaskAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI> {
    return this.postTask(taskdb, GONG__StackPath, frontRepo)
  }
  postTask(taskdb: TaskAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TaskAPI>(this.tasksUrl, taskdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted taskdb id=${taskdb.ID}`)
      }),
      catchError(this.handleError<TaskAPI>('postTask'))
    );
  }

  /** DELETE: delete the taskdb from the server */
  delete(taskdb: TaskAPI | number, GONG__StackPath: string): Observable<TaskAPI> {
    return this.deleteTask(taskdb, GONG__StackPath)
  }
  deleteTask(taskdb: TaskAPI | number, GONG__StackPath: string): Observable<TaskAPI> {
    const id = typeof taskdb === 'number' ? taskdb : taskdb.ID;
    const url = `${this.tasksUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<TaskAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted taskdb id=${id}`)),
      catchError(this.handleError<TaskAPI>('deleteTask'))
    );
  }

  // updateFront copy task to a version with encoded pointers and update to the back
  updateFront(task: Task, GONG__StackPath: string): Observable<TaskAPI> {
    let taskAPI = new TaskAPI
    CopyTaskToTaskAPI(task, taskAPI)
    const id = typeof taskAPI === 'number' ? taskAPI : taskAPI.ID
    const url = `${this.tasksUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<TaskAPI>(url, taskAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<TaskAPI>('updateTask'))
    );
  }

  /** PUT: update the taskdb on the server */
  update(taskdb: TaskAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI> {
    return this.updateTask(taskdb, GONG__StackPath, frontRepo)
  }
  updateTask(taskdb: TaskAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<TaskAPI> {
    const id = typeof taskdb === 'number' ? taskdb : taskdb.ID;
    const url = `${this.tasksUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<TaskAPI>(url, taskdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated taskdb id=${taskdb.ID}`)
      }),
      catchError(this.handleError<TaskAPI>('updateTask'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in TaskService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("TaskService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
